### PR TITLE
added ci yaml file

### PR DESCRIPTION
**Pull request by mckornfield**
* adds a CI file so that we can tell whether or not code changes break the build

### CODE REVIEW

**Comment by mckornfield** [comment]
@deepwinter Ready for review.  you can see the travis link on the checks page.

**Comment by deepwinter** [comment]
@mckornfield Should this be merged?

**Comment by mckornfield** [comment]
Yep it can be. I just need to rebase.

**Comment by mckornfield** [comment]
Looks like I had to change some things based on the config file movement. Also one of the tests always fails (the test-int ones). Not sure what to do to get it to pass

**Comment by deepwinter** [comment]
Gonna go ahead and merge this.

**Comment by mckornfield** [comment]
Yep fine to merge. Need to fail the build for this issue https://travis-ci.com/Greenstand/treetracker-mobile-api/builds/109428895#L519 or fix it

**Pull request merged**
